{{- if .Values.manageSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langtail.fullname" . }}-secret
type: Opaque
data:
  LANGTAIL_LICENSE_KEY: {{ .Values.LANGTAIL_LICENSE_KEY | toString | b64enc | quote }}
  DATABASE_URL: {{ .Values.DATABASE_URL | toString | b64enc | quote }}
  PRISMA_FIELD_ENCRYPTION_KEY: {{ .Values.PRISMA_FIELD_ENCRYPTION_KEY | toString | b64enc | quote }}
  JWT_PRIVATE: {{ .Values.JWT_PRIVATE | toString | b64enc | quote }}
  JWT_PUBLIC: {{ .Values.JWT_PUBLIC | toString | b64enc | quote }}
  IMAGES_AWS_SECRET_ACCESS_KEY: {{ .Values.IMAGES_AWS_SECRET_ACCESS_KEY | toString | b64enc | quote }}
  AUTH_SECRET: {{ .Values.AUTH_SECRET | toString | b64enc | quote }}
  GITHUB_SECRET: {{ .Values.GITHUB_SECRET | toString | b64enc | quote }}
  GOOGLE_SECRET: {{ .Values.GOOGLE_SECRET | toString | b64enc | quote }}
  JWT_SIGNING_KEY: {{ .Values.JWT_SIGNING_KEY | toString | b64enc | quote }}
  SMTP_URL: {{ .Values.SMTP_URL | toString | b64enc | quote }}
  EMAIL_VERIFICATION_SECRET: {{ .Values.EMAIL_VERIFICATION_SECRET | toString | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langtail.fullname" . }}-migrations-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  LANGTAIL_LICENSE_KEY: {{ .Values.LANGTAIL_LICENSE_KEY | toString | b64enc | quote }}
  DATABASE_URL: {{ .Values.MIGRATIONS_DATABASE_URL | toString | b64enc | quote }}
{{- end }}
